// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileInfo struct {
	FormatVersion        int32    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFormatVersion() int32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

type Entry struct {
	// Types that are valid to be assigned to Entry:
	//	*Entry_Qso
	//	*Entry_Station
	//	*Entry_Contest
	//	*Entry_Keyer
	Entry                isEntry_Entry `protobuf_oneof:"entry"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

type isEntry_Entry interface {
	isEntry_Entry()
}

type Entry_Qso struct {
	Qso *QSO `protobuf:"bytes,1,opt,name=qso,proto3,oneof"`
}

type Entry_Station struct {
	Station *Station `protobuf:"bytes,2,opt,name=station,proto3,oneof"`
}

type Entry_Contest struct {
	Contest *Contest `protobuf:"bytes,3,opt,name=contest,proto3,oneof"`
}

type Entry_Keyer struct {
	Keyer *Keyer `protobuf:"bytes,4,opt,name=keyer,proto3,oneof"`
}

func (*Entry_Qso) isEntry_Entry() {}

func (*Entry_Station) isEntry_Entry() {}

func (*Entry_Contest) isEntry_Entry() {}

func (*Entry_Keyer) isEntry_Entry() {}

func (m *Entry) GetEntry() isEntry_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Entry) GetQso() *QSO {
	if x, ok := m.GetEntry().(*Entry_Qso); ok {
		return x.Qso
	}
	return nil
}

func (m *Entry) GetStation() *Station {
	if x, ok := m.GetEntry().(*Entry_Station); ok {
		return x.Station
	}
	return nil
}

func (m *Entry) GetContest() *Contest {
	if x, ok := m.GetEntry().(*Entry_Contest); ok {
		return x.Contest
	}
	return nil
}

func (m *Entry) GetKeyer() *Keyer {
	if x, ok := m.GetEntry().(*Entry_Keyer); ok {
		return x.Keyer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entry_Qso)(nil),
		(*Entry_Station)(nil),
		(*Entry_Contest)(nil),
		(*Entry_Keyer)(nil),
	}
}

type QSO struct {
	Callsign             string   `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Band                 string   `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"`
	Mode                 string   `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	MyReport             string   `protobuf:"bytes,5,opt,name=my_report,json=myReport,proto3" json:"my_report,omitempty"`
	MyNumber             int32    `protobuf:"varint,6,opt,name=my_number,json=myNumber,proto3" json:"my_number,omitempty"`
	TheirReport          string   `protobuf:"bytes,7,opt,name=their_report,json=theirReport,proto3" json:"their_report,omitempty"`
	TheirNumber          int32    `protobuf:"varint,8,opt,name=their_number,json=theirNumber,proto3" json:"their_number,omitempty"`
	LogTimestamp         int64    `protobuf:"varint,9,opt,name=log_timestamp,json=logTimestamp,proto3" json:"log_timestamp,omitempty"`
	MyXchange            string   `protobuf:"bytes,10,opt,name=my_xchange,json=myXchange,proto3" json:"my_xchange,omitempty"`
	TheirXchange         string   `protobuf:"bytes,11,opt,name=their_xchange,json=theirXchange,proto3" json:"their_xchange,omitempty"`
	Frequency            float64  `protobuf:"fixed64,12,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QSO) Reset()         { *m = QSO{} }
func (m *QSO) String() string { return proto.CompactTextString(m) }
func (*QSO) ProtoMessage()    {}
func (*QSO) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *QSO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QSO.Unmarshal(m, b)
}
func (m *QSO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QSO.Marshal(b, m, deterministic)
}
func (m *QSO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QSO.Merge(m, src)
}
func (m *QSO) XXX_Size() int {
	return xxx_messageInfo_QSO.Size(m)
}
func (m *QSO) XXX_DiscardUnknown() {
	xxx_messageInfo_QSO.DiscardUnknown(m)
}

var xxx_messageInfo_QSO proto.InternalMessageInfo

func (m *QSO) GetCallsign() string {
	if m != nil {
		return m.Callsign
	}
	return ""
}

func (m *QSO) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QSO) GetBand() string {
	if m != nil {
		return m.Band
	}
	return ""
}

func (m *QSO) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *QSO) GetMyReport() string {
	if m != nil {
		return m.MyReport
	}
	return ""
}

func (m *QSO) GetMyNumber() int32 {
	if m != nil {
		return m.MyNumber
	}
	return 0
}

func (m *QSO) GetTheirReport() string {
	if m != nil {
		return m.TheirReport
	}
	return ""
}

func (m *QSO) GetTheirNumber() int32 {
	if m != nil {
		return m.TheirNumber
	}
	return 0
}

func (m *QSO) GetLogTimestamp() int64 {
	if m != nil {
		return m.LogTimestamp
	}
	return 0
}

func (m *QSO) GetMyXchange() string {
	if m != nil {
		return m.MyXchange
	}
	return ""
}

func (m *QSO) GetTheirXchange() string {
	if m != nil {
		return m.TheirXchange
	}
	return ""
}

func (m *QSO) GetFrequency() float64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type Station struct {
	Callsign             string   `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Locator              string   `protobuf:"bytes,3,opt,name=locator,proto3" json:"locator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetCallsign() string {
	if m != nil {
		return m.Callsign
	}
	return ""
}

func (m *Station) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Station) GetLocator() string {
	if m != nil {
		return m.Locator
	}
	return ""
}

type Contest struct {
	Name                    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnterTheirNumber        bool     `protobuf:"varint,2,opt,name=enter_their_number,json=enterTheirNumber,proto3" json:"enter_their_number,omitempty"`
	EnterTheirXchange       bool     `protobuf:"varint,3,opt,name=enter_their_xchange,json=enterTheirXchange,proto3" json:"enter_their_xchange,omitempty"`
	RequireTheirXchange     bool     `protobuf:"varint,4,opt,name=require_their_xchange,json=requireTheirXchange,proto3" json:"require_their_xchange,omitempty"`
	AllowMultiBand          bool     `protobuf:"varint,5,opt,name=allow_multi_band,json=allowMultiBand,proto3" json:"allow_multi_band,omitempty"`
	AllowMultiMode          bool     `protobuf:"varint,6,opt,name=allow_multi_mode,json=allowMultiMode,proto3" json:"allow_multi_mode,omitempty"`
	SameCountryPoints       int32    `protobuf:"varint,7,opt,name=same_country_points,json=sameCountryPoints,proto3" json:"same_country_points,omitempty"`
	SameContinentPoints     int32    `protobuf:"varint,8,opt,name=same_continent_points,json=sameContinentPoints,proto3" json:"same_continent_points,omitempty"`
	SpecificCountryPoints   int32    `protobuf:"varint,9,opt,name=specific_country_points,json=specificCountryPoints,proto3" json:"specific_country_points,omitempty"`
	SpecificCountryPrefixes []string `protobuf:"bytes,10,rep,name=specific_country_prefixes,json=specificCountryPrefixes,proto3" json:"specific_country_prefixes,omitempty"`
	OtherPoints             int32    `protobuf:"varint,11,opt,name=other_points,json=otherPoints,proto3" json:"other_points,omitempty"`
	Multis                  *Multis  `protobuf:"bytes,12,opt,name=multis,proto3" json:"multis,omitempty"`
	XchangeMultiPattern     string   `protobuf:"bytes,13,opt,name=xchange_multi_pattern,json=xchangeMultiPattern,proto3" json:"xchange_multi_pattern,omitempty"`
	CountPerBand            bool     `protobuf:"varint,14,opt,name=count_per_band,json=countPerBand,proto3" json:"count_per_band,omitempty"`
	CabrilloQsoTemplate     string   `protobuf:"bytes,15,opt,name=cabrillo_qso_template,json=cabrilloQsoTemplate,proto3" json:"cabrillo_qso_template,omitempty"`
	CallHistoryFilename     string   `protobuf:"bytes,16,opt,name=call_history_filename,json=callHistoryFilename,proto3" json:"call_history_filename,omitempty"`
	CallHistoryField        string   `protobuf:"bytes,17,opt,name=call_history_field,json=callHistoryField,proto3" json:"call_history_field,omitempty"`
	DefinitionYaml          string   `protobuf:"bytes,18,opt,name=definition_yaml,json=definitionYaml,proto3" json:"definition_yaml,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Contest) Reset()         { *m = Contest{} }
func (m *Contest) String() string { return proto.CompactTextString(m) }
func (*Contest) ProtoMessage()    {}
func (*Contest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *Contest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contest.Unmarshal(m, b)
}
func (m *Contest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contest.Marshal(b, m, deterministic)
}
func (m *Contest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contest.Merge(m, src)
}
func (m *Contest) XXX_Size() int {
	return xxx_messageInfo_Contest.Size(m)
}
func (m *Contest) XXX_DiscardUnknown() {
	xxx_messageInfo_Contest.DiscardUnknown(m)
}

var xxx_messageInfo_Contest proto.InternalMessageInfo

func (m *Contest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contest) GetEnterTheirNumber() bool {
	if m != nil {
		return m.EnterTheirNumber
	}
	return false
}

func (m *Contest) GetEnterTheirXchange() bool {
	if m != nil {
		return m.EnterTheirXchange
	}
	return false
}

func (m *Contest) GetRequireTheirXchange() bool {
	if m != nil {
		return m.RequireTheirXchange
	}
	return false
}

func (m *Contest) GetAllowMultiBand() bool {
	if m != nil {
		return m.AllowMultiBand
	}
	return false
}

func (m *Contest) GetAllowMultiMode() bool {
	if m != nil {
		return m.AllowMultiMode
	}
	return false
}

func (m *Contest) GetSameCountryPoints() int32 {
	if m != nil {
		return m.SameCountryPoints
	}
	return 0
}

func (m *Contest) GetSameContinentPoints() int32 {
	if m != nil {
		return m.SameContinentPoints
	}
	return 0
}

func (m *Contest) GetSpecificCountryPoints() int32 {
	if m != nil {
		return m.SpecificCountryPoints
	}
	return 0
}

func (m *Contest) GetSpecificCountryPrefixes() []string {
	if m != nil {
		return m.SpecificCountryPrefixes
	}
	return nil
}

func (m *Contest) GetOtherPoints() int32 {
	if m != nil {
		return m.OtherPoints
	}
	return 0
}

func (m *Contest) GetMultis() *Multis {
	if m != nil {
		return m.Multis
	}
	return nil
}

func (m *Contest) GetXchangeMultiPattern() string {
	if m != nil {
		return m.XchangeMultiPattern
	}
	return ""
}

func (m *Contest) GetCountPerBand() bool {
	if m != nil {
		return m.CountPerBand
	}
	return false
}

func (m *Contest) GetCabrilloQsoTemplate() string {
	if m != nil {
		return m.CabrilloQsoTemplate
	}
	return ""
}

func (m *Contest) GetCallHistoryFilename() string {
	if m != nil {
		return m.CallHistoryFilename
	}
	return ""
}

func (m *Contest) GetCallHistoryField() string {
	if m != nil {
		return m.CallHistoryField
	}
	return ""
}

func (m *Contest) GetDefinitionYaml() string {
	if m != nil {
		return m.DefinitionYaml
	}
	return ""
}

type Multis struct {
	Dxcc                 bool     `protobuf:"varint,1,opt,name=dxcc,proto3" json:"dxcc,omitempty"`
	Wpx                  bool     `protobuf:"varint,2,opt,name=wpx,proto3" json:"wpx,omitempty"`
	Xchange              bool     `protobuf:"varint,3,opt,name=xchange,proto3" json:"xchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Multis) Reset()         { *m = Multis{} }
func (m *Multis) String() string { return proto.CompactTextString(m) }
func (*Multis) ProtoMessage()    {}
func (*Multis) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *Multis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Multis.Unmarshal(m, b)
}
func (m *Multis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Multis.Marshal(b, m, deterministic)
}
func (m *Multis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Multis.Merge(m, src)
}
func (m *Multis) XXX_Size() int {
	return xxx_messageInfo_Multis.Size(m)
}
func (m *Multis) XXX_DiscardUnknown() {
	xxx_messageInfo_Multis.DiscardUnknown(m)
}

var xxx_messageInfo_Multis proto.InternalMessageInfo

func (m *Multis) GetDxcc() bool {
	if m != nil {
		return m.Dxcc
	}
	return false
}

func (m *Multis) GetWpx() bool {
	if m != nil {
		return m.Wpx
	}
	return false
}

func (m *Multis) GetXchange() bool {
	if m != nil {
		return m.Xchange
	}
	return false
}

type Keyer struct {
	Wpm                  int32    `protobuf:"varint,1,opt,name=wpm,proto3" json:"wpm,omitempty"`
	SpMacros             []string `protobuf:"bytes,2,rep,name=sp_macros,json=spMacros,proto3" json:"sp_macros,omitempty"`
	RunMacros            []string `protobuf:"bytes,3,rep,name=run_macros,json=runMacros,proto3" json:"run_macros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keyer) Reset()         { *m = Keyer{} }
func (m *Keyer) String() string { return proto.CompactTextString(m) }
func (*Keyer) ProtoMessage()    {}
func (*Keyer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{6}
}

func (m *Keyer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keyer.Unmarshal(m, b)
}
func (m *Keyer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keyer.Marshal(b, m, deterministic)
}
func (m *Keyer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keyer.Merge(m, src)
}
func (m *Keyer) XXX_Size() int {
	return xxx_messageInfo_Keyer.Size(m)
}
func (m *Keyer) XXX_DiscardUnknown() {
	xxx_messageInfo_Keyer.DiscardUnknown(m)
}

var xxx_messageInfo_Keyer proto.InternalMessageInfo

func (m *Keyer) GetWpm() int32 {
	if m != nil {
		return m.Wpm
	}
	return 0
}

func (m *Keyer) GetSpMacros() []string {
	if m != nil {
		return m.SpMacros
	}
	return nil
}

func (m *Keyer) GetRunMacros() []string {
	if m != nil {
		return m.RunMacros
	}
	return nil
}

func init() {
	proto.RegisterType((*FileInfo)(nil), "pb.FileInfo")
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*QSO)(nil), "pb.QSO")
	proto.RegisterType((*Station)(nil), "pb.Station")
	proto.RegisterType((*Contest)(nil), "pb.Contest")
	proto.RegisterType((*Multis)(nil), "pb.Multis")
	proto.RegisterType((*Keyer)(nil), "pb.Keyer")
}

func init() {
	proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886)
}

var fileDescriptor_a153da538f858886 = []byte{
	// 837 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xaf, 0xe3, 0xd8, 0xbe, 0x1b, 0x27, 0xae, 0xb3, 0x56, 0xd4, 0xa3, 0x2d, 0x52, 0x6a, 0x40,
	0xcd, 0x03, 0xb2, 0x44, 0x90, 0x78, 0xe0, 0xb1, 0x15, 0x95, 0x01, 0x85, 0x26, 0x97, 0x80, 0x40,
	0x3c, 0x9c, 0xce, 0xe7, 0xb1, 0xb3, 0x62, 0xff, 0x5c, 0x76, 0xd7, 0x34, 0xf7, 0x75, 0xf8, 0x1a,
	0x7c, 0x2d, 0x3e, 0x00, 0xda, 0xd9, 0xbd, 0xb8, 0x36, 0x12, 0x6f, 0xbb, 0xbf, 0x3f, 0x33, 0x3b,
	0xb3, 0xb3, 0x77, 0x90, 0x0a, 0xbd, 0x9e, 0xd5, 0x46, 0x3b, 0xcd, 0x0e, 0xea, 0xc5, 0xf4, 0x2b,
	0x48, 0xde, 0x71, 0x81, 0xdf, 0xab, 0x95, 0x66, 0x5f, 0xc0, 0x68, 0xa5, 0x8d, 0x2c, 0x5d, 0xf1,
	0x27, 0x1a, 0xcb, 0xb5, 0xca, 0x3a, 0x67, 0x9d, 0xf3, 0x5e, 0x7e, 0x1c, 0xd0, 0x5f, 0x02, 0x38,
	0xfd, 0xab, 0x03, 0xbd, 0xef, 0x94, 0x33, 0x0d, 0x7b, 0x01, 0xdd, 0x7b, 0xab, 0x49, 0x35, 0xbc,
	0x18, 0xcc, 0xea, 0xc5, 0xec, 0xfa, 0xe6, 0xfd, 0xfc, 0x49, 0xee, 0x51, 0xf6, 0x1a, 0x06, 0xd6,
	0x95, 0xce, 0x87, 0x39, 0x20, 0xc1, 0xd0, 0x0b, 0x6e, 0x02, 0x34, 0x7f, 0x92, 0xb7, 0xac, 0x17,
	0x56, 0x5a, 0x39, 0xb4, 0x2e, 0xeb, 0x6e, 0x85, 0x6f, 0x03, 0xe4, 0x85, 0x91, 0x65, 0xaf, 0xa0,
	0xf7, 0x07, 0x36, 0x68, 0xb2, 0x43, 0x92, 0xa5, 0x5e, 0xf6, 0xa3, 0x07, 0xe6, 0x4f, 0xf2, 0xc0,
	0xbc, 0x19, 0x40, 0x0f, 0xfd, 0xd1, 0xa6, 0xff, 0x1c, 0x40, 0xf7, 0xfa, 0xe6, 0x3d, 0x7b, 0x0e,
	0x49, 0x55, 0x0a, 0x61, 0xf9, 0x3a, 0x54, 0x93, 0xe6, 0x8f, 0x7b, 0xf6, 0x12, 0x52, 0xc7, 0x25,
	0x5a, 0x57, 0xca, 0x9a, 0xce, 0xd8, 0xcd, 0xb7, 0x00, 0x63, 0x70, 0xb8, 0x28, 0xd5, 0x92, 0xce,
	0x94, 0xe6, 0xb4, 0xf6, 0x98, 0xd4, 0x4b, 0xa4, 0x03, 0xa4, 0x39, 0xad, 0xd9, 0x0b, 0x48, 0x65,
	0x53, 0x18, 0xac, 0xb5, 0x71, 0x59, 0x2f, 0xa4, 0x90, 0x4d, 0x4e, 0xfb, 0x48, 0xaa, 0x8d, 0x5c,
	0xa0, 0xc9, 0xfa, 0xd4, 0xcd, 0x44, 0x36, 0x3f, 0xd1, 0x9e, 0xbd, 0x82, 0x23, 0x77, 0x87, 0xdc,
	0xb4, 0xe6, 0x01, 0x99, 0x87, 0x84, 0x45, 0xff, 0xa3, 0x24, 0x86, 0x48, 0x28, 0x44, 0x90, 0xc4,
	0x28, 0x9f, 0xc1, 0xb1, 0xd0, 0xeb, 0x62, 0x5b, 0x49, 0x4a, 0x95, 0x1c, 0x09, 0xbd, 0xbe, 0x7d,
	0x2c, 0xe6, 0x53, 0x00, 0xd9, 0x14, 0x0f, 0xd5, 0x5d, 0xa9, 0xd6, 0x98, 0x01, 0x25, 0x4a, 0x65,
	0xf3, 0x6b, 0x00, 0x7c, 0x8c, 0x90, 0xa6, 0x55, 0x0c, 0x49, 0x11, 0x72, 0xb7, 0xa2, 0x97, 0x90,
	0xae, 0x0c, 0xde, 0x6f, 0x50, 0x55, 0x4d, 0x76, 0x74, 0xd6, 0x39, 0xef, 0xe4, 0x5b, 0xe0, 0x87,
	0xc3, 0xe4, 0x78, 0x3c, 0x9a, 0xfe, 0x0e, 0x83, 0x78, 0xc3, 0xff, 0xdb, 0xf9, 0xe7, 0x90, 0xe8,
	0x1a, 0x4d, 0xe9, 0xb4, 0xa1, 0xc6, 0xa7, 0xf9, 0xe3, 0x9e, 0x65, 0x30, 0x10, 0xba, 0x22, 0x2a,
	0xb4, 0xbe, 0xdd, 0x4e, 0xff, 0xee, 0xc3, 0x20, 0x8e, 0x85, 0xbf, 0x09, 0x55, 0x4a, 0x8c, 0x91,
	0x69, 0xcd, 0xbe, 0x04, 0x86, 0xca, 0xa1, 0x29, 0x76, 0x5a, 0xe6, 0xe3, 0x27, 0xf9, 0x98, 0x98,
	0xdb, 0x8f, 0xfa, 0x36, 0x83, 0xc9, 0xc7, 0xea, 0xb6, 0xf2, 0x2e, 0xc9, 0x4f, 0xb6, 0xf2, 0xb6,
	0xfc, 0x0b, 0x38, 0xf5, 0xc5, 0x72, 0x83, 0x7b, 0x8e, 0x43, 0x72, 0x4c, 0x22, 0xb9, 0xe3, 0x39,
	0x87, 0x71, 0x29, 0x84, 0xfe, 0x50, 0xc8, 0x8d, 0x70, 0xbc, 0xa0, 0x79, 0xea, 0x91, 0x7c, 0x44,
	0xf8, 0xa5, 0x87, 0xdf, 0xf8, 0xc9, 0xda, 0x53, 0xd2, 0x94, 0xf5, 0xf7, 0x95, 0x97, 0x7e, 0xde,
	0x66, 0x30, 0xb1, 0xa5, 0xc4, 0xa2, 0xd2, 0x1b, 0x3f, 0xe9, 0x45, 0xad, 0xb9, 0x72, 0x96, 0x86,
	0xa7, 0x97, 0x9f, 0x78, 0xea, 0x6d, 0x60, 0xae, 0x88, 0xf0, 0xe7, 0x8e, 0x7a, 0xe5, 0xb8, 0x42,
	0xe5, 0x5a, 0x47, 0x98, 0xa5, 0x49, 0x70, 0x44, 0x2e, 0x7a, 0xbe, 0x81, 0x67, 0xb6, 0xc6, 0x8a,
	0xaf, 0x78, 0xb5, 0x9f, 0x27, 0x25, 0xd7, 0x69, 0x4b, 0xef, 0xe6, 0xfa, 0x16, 0x3e, 0xf9, 0xaf,
	0xcf, 0xe0, 0x8a, 0x3f, 0xa0, 0xcd, 0xe0, 0xac, 0x7b, 0x9e, 0xe6, 0xcf, 0xf6, 0x9d, 0x91, 0xf6,
	0xa3, 0xae, 0xdd, 0x1d, 0x9a, 0x36, 0xd1, 0x30, 0x8c, 0x3a, 0x61, 0x31, 0xfc, 0x14, 0xfa, 0xd4,
	0x1e, 0x4b, 0xe3, 0x37, 0xbc, 0x00, 0xff, 0x05, 0xa0, 0xce, 0xd8, 0x3c, 0x32, 0xbe, 0xdc, 0x78,
	0x31, 0xb1, 0x95, 0x75, 0xe9, 0x1c, 0x1a, 0x95, 0x1d, 0xd3, 0xa4, 0x4c, 0x22, 0x49, 0xae, 0xab,
	0x40, 0xb1, 0xcf, 0x61, 0x44, 0xa7, 0x2d, 0x6a, 0x34, 0xe1, 0x92, 0x46, 0xd4, 0xfa, 0x23, 0x42,
	0xaf, 0xd0, 0xd0, 0x15, 0x5d, 0xc0, 0x69, 0x55, 0x2e, 0x0c, 0x17, 0x42, 0x17, 0xf7, 0x56, 0x17,
	0x0e, 0x65, 0x2d, 0x4a, 0x87, 0xd9, 0xd3, 0x10, 0xb9, 0x25, 0xaf, 0xad, 0xbe, 0x8d, 0x54, 0xf0,
	0x08, 0x51, 0xdc, 0x71, 0xeb, 0xb4, 0x69, 0x8a, 0x15, 0x17, 0x48, 0x73, 0x3b, 0x6e, 0x3d, 0x42,
	0xcc, 0x03, 0xf7, 0x2e, 0x52, 0x7e, 0x8c, 0xf7, 0x3c, 0x28, 0x96, 0xd9, 0x09, 0x19, 0xc6, 0x3b,
	0x06, 0x14, 0x4b, 0xf6, 0x1a, 0x9e, 0x2e, 0x71, 0xc5, 0x15, 0xf7, 0x8f, 0xae, 0x68, 0x4a, 0x29,
	0x32, 0x46, 0xd2, 0xd1, 0x16, 0xfe, 0xad, 0x94, 0x62, 0x3a, 0x87, 0x7e, 0x68, 0x95, 0x7f, 0x3b,
	0xcb, 0x87, 0xaa, 0xa2, 0xb7, 0x93, 0xe4, 0xb4, 0x66, 0x63, 0xe8, 0x7e, 0xa8, 0x1f, 0xe2, 0x63,
	0xf1, 0x4b, 0xff, 0x0e, 0x77, 0xdf, 0x44, 0xbb, 0x9d, 0xfe, 0x0c, 0x3d, 0xfa, 0xec, 0x06, 0x93,
	0x8c, 0x7f, 0x09, 0xbf, 0xf4, 0xdf, 0x3b, 0x5b, 0x17, 0xb2, 0xac, 0x8c, 0xb6, 0xd9, 0x01, 0x5d,
	0x78, 0x62, 0xeb, 0x4b, 0xda, 0xfb, 0x8f, 0x90, 0xd9, 0xa8, 0x96, 0xed, 0x12, 0x9b, 0x9a, 0x8d,
	0x0a, 0xf4, 0xa2, 0x4f, 0x7f, 0xa5, 0xaf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x76, 0x39, 0x1c,
	0x55, 0xa2, 0x06, 0x00, 0x00,
}
