// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geometry.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Windows struct {
	Windows              []*Window `protobuf:"bytes,1,rep,name=windows" json:"windows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Windows) Reset()         { *m = Windows{} }
func (m *Windows) String() string { return proto.CompactTextString(m) }
func (*Windows) ProtoMessage()    {}
func (*Windows) Descriptor() ([]byte, []int) {
	return fileDescriptor_geometry_d109d3ad4502ace6, []int{0}
}
func (m *Windows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Windows.Unmarshal(m, b)
}
func (m *Windows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Windows.Marshal(b, m, deterministic)
}
func (dst *Windows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Windows.Merge(dst, src)
}
func (m *Windows) XXX_Size() int {
	return xxx_messageInfo_Windows.Size(m)
}
func (m *Windows) XXX_DiscardUnknown() {
	xxx_messageInfo_Windows.DiscardUnknown(m)
}

var xxx_messageInfo_Windows proto.InternalMessageInfo

func (m *Windows) GetWindows() []*Window {
	if m != nil {
		return m.Windows
	}
	return nil
}

type Window struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Size                 *Size     `protobuf:"bytes,3,opt,name=size" json:"size,omitempty"`
	Maximized            bool      `protobuf:"varint,4,opt,name=maximized" json:"maximized,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Window) Reset()         { *m = Window{} }
func (m *Window) String() string { return proto.CompactTextString(m) }
func (*Window) ProtoMessage()    {}
func (*Window) Descriptor() ([]byte, []int) {
	return fileDescriptor_geometry_d109d3ad4502ace6, []int{1}
}
func (m *Window) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Window.Unmarshal(m, b)
}
func (m *Window) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Window.Marshal(b, m, deterministic)
}
func (dst *Window) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Window.Merge(dst, src)
}
func (m *Window) XXX_Size() int {
	return xxx_messageInfo_Window.Size(m)
}
func (m *Window) XXX_DiscardUnknown() {
	xxx_messageInfo_Window.DiscardUnknown(m)
}

var xxx_messageInfo_Window proto.InternalMessageInfo

func (m *Window) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Window) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Window) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Window) GetMaximized() bool {
	if m != nil {
		return m.Maximized
	}
	return false
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_geometry_d109d3ad4502ace6, []int{2}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Size struct {
	Width                int32    `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_geometry_d109d3ad4502ace6, []int{3}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Size) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Windows)(nil), "pb.Windows")
	proto.RegisterType((*Window)(nil), "pb.Window")
	proto.RegisterType((*Position)(nil), "pb.Position")
	proto.RegisterType((*Size)(nil), "pb.Size")
}

func init() { proto.RegisterFile("geometry.proto", fileDescriptor_geometry_d109d3ad4502ace6) }

var fileDescriptor_geometry_d109d3ad4502ace6 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3f, 0x6b, 0xc3, 0x30,
	0x14, 0xc4, 0x79, 0x89, 0xed, 0x38, 0x2f, 0xa1, 0xc3, 0xa3, 0x14, 0x0d, 0x19, 0x8c, 0x29, 0x45,
	0x93, 0x0b, 0x69, 0x3f, 0x48, 0x51, 0x87, 0xce, 0x31, 0x16, 0xf1, 0x1b, 0x6c, 0x99, 0x58, 0xe0,
	0x3f, 0x63, 0x3f, 0x79, 0xd1, 0x9f, 0x34, 0xdb, 0xdd, 0xef, 0x4e, 0x27, 0x21, 0x7c, 0xba, 0x6a,
	0xd3, 0x69, 0x7b, 0x5b, 0xaa, 0xe1, 0x66, 0xac, 0xa1, 0xcd, 0x50, 0x97, 0xef, 0xb8, 0xfb, 0xe1,
	0xbe, 0x31, 0xd3, 0x48, 0xaf, 0xb8, 0x9b, 0x82, 0x14, 0x50, 0x6c, 0xe5, 0xe1, 0x8c, 0xd5, 0x50,
	0x57, 0x21, 0x55, 0xf7, 0xa8, 0xfc, 0x05, 0xcc, 0x02, 0x23, 0xc2, 0xa4, 0xbf, 0x74, 0x5a, 0x40,
	0x01, 0x72, 0xaf, 0xbc, 0x26, 0x89, 0xf9, 0x60, 0x46, 0xb6, 0x6c, 0x7a, 0xb1, 0x29, 0x40, 0x1e,
	0xce, 0x47, 0xb7, 0xf2, 0x15, 0x99, 0xfa, 0x4f, 0xe9, 0x84, 0xc9, 0xc8, 0xab, 0x16, 0x5b, 0xdf,
	0xca, 0x5d, 0xeb, 0x9b, 0x57, 0xad, 0x3c, 0xa5, 0x13, 0xee, 0xbb, 0xcb, 0xcc, 0x1d, 0xaf, 0xba,
	0x11, 0x49, 0x01, 0x32, 0x57, 0x0f, 0x50, 0xbe, 0x61, 0x7e, 0x5f, 0xa4, 0x23, 0xc2, 0xec, 0x9f,
	0x90, 0x2a, 0x98, 0x9d, 0x5b, 0xfc, 0xc5, 0xa9, 0x82, 0xa5, 0xfc, 0xc4, 0xc4, 0x6d, 0xd2, 0x33,
	0xa6, 0x13, 0x37, 0xb6, 0x8d, 0xbd, 0x60, 0xe8, 0x05, 0xb3, 0x56, 0xf3, 0xb5, 0xb5, 0xf1, 0x40,
	0x74, 0x75, 0xe6, 0xbf, 0xe7, 0xe3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x6b, 0x54, 0x85, 0x30,
	0x01, 0x00, 0x00,
}
