// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package session

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State struct {
	LastFilename         string   `protobuf:"bytes,1,opt,name=last_filename,json=lastFilename,proto3" json:"last_filename,omitempty"`
	SendSpotsToTci       bool     `protobuf:"varint,2,opt,name=send_spots_to_tci,json=sendSpotsToTci,proto3" json:"send_spots_to_tci,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetLastFilename() string {
	if m != nil {
		return m.LastFilename
	}
	return ""
}

func (m *State) GetSendSpotsToTci() bool {
	if m != nil {
		return m.SendSpotsToTci
	}
	return false
}

func init() {
	proto.RegisterType((*State)(nil), "session.State")
}

func init() {
	proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14)
}

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xc2, 0xb9,
	0x58, 0x83, 0x4b, 0x12, 0x4b, 0x52, 0x85, 0x94, 0xb9, 0x78, 0x73, 0x12, 0x8b, 0x4b, 0xe2, 0xd3,
	0x32, 0x73, 0x52, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x78, 0x40,
	0x82, 0x6e, 0x50, 0x31, 0x21, 0x4d, 0x2e, 0xc1, 0xe2, 0xd4, 0xbc, 0x94, 0xf8, 0xe2, 0x82, 0xfc,
	0x92, 0xe2, 0xf8, 0x92, 0xfc, 0xf8, 0x92, 0xe4, 0x4c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20,
	0x3e, 0x90, 0x44, 0x30, 0x48, 0x3c, 0x24, 0x3f, 0x24, 0x39, 0x33, 0x89, 0x0d, 0x6c, 0x91, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x68, 0x34, 0x60, 0x4a, 0x79, 0x00, 0x00, 0x00,
}
