name: CI-Build

on:
  push:
    branches: 
    - master
    - "**"
  pull_request:
    branches: 
    - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      version_number: ${{ steps.version_number.outputs.version_number }}
    steps:
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends libgtk-3-0 libgtk-3-dev libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go 1.22.3
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
      id: go

    - name: Get Gtk version and the environment
      run: pkg-config --modversion gtk+-3.0;env
    
    - name: Version Number
      id: version_number
      run: echo "version_number=$(make version_number)" >> $GITHUB_OUTPUT

    - name: Show Version
      run: echo "Version ${{ steps.version_number.outputs.version_number }}"

    - name: Build
      run: 
        make deps test build
    
    - name: 'Upload binary for linux_x86_64'
      uses: actions/upload-artifact@v3
      with:
        name: hellocontest-binary
        path: ./hellocontest
